### ISSUE TITLE
index.html not rendering or showing what gama_client.js is supposed to show

### ISSUE THREAD

**Issue by xiaofanliang** [gama-platform/gama.client#2]
Hi great people! 

Thanks for investing in my issues. 

I found the GAMA headless server https://gama-platform.org/wiki/HeadlessServer#hello-world-visualization-in-mapbox and tried to run a copy on my local machine. I had not been successful yet (elaboration below). I assume this server and the JS client allow me to run and show GAMA simulation results on the web. Have there been any successful examples deployed on the web that I can click and see? 

For the issue I ran into, here is an elaboration: 

I am using a MacOS M1 Chip computer, with a M1 chip GAMA installation. I followed the steps in this webpage: https://gama-platform.org/wiki/HeadlessServer#hello-world-visualization-in-mapbox to start a headless server and try to run the HellowWorld Visualization in Mapbox (JS client). 
 
To start the server, I entered the following codes in my terminal: 
```
cd Gama.app/Contents/headless
bash gama-headless.sh -socket 6868
```
The server seems to start fine: 
![Screen Shot 2023-02-08 at 11 31 06 AM](https://user-images.githubusercontent.com/22874361/217598206-16abd033-28fc-4475-b806-7eb9bbf56a3c.png)

Then, I go to the gama.client.js to modify the path of the library model file (highlighted). The path is found by opening the specific library model in local GAMA software, going to File -> Properties -> Location. 

I uncommented the example that is on road traffic and commented out all other examples (see below). 

![Screen Shot 2023-02-08 at 11 32 58 AM](https://user-images.githubusercontent.com/22874361/217598309-8aae0248-04c5-4d73-8f5d-5d908b895a74.png)

Then in the same gama_client.js, I modify the local path to Websocket to ws://localhost:6868/, because that is the port in the server. 

![Screen Shot 2023-02-08 at 11 35 00 AM](https://user-images.githubusercontent.com/22874361/217598340-80490810-1e71-4e48-af05-b5bf8c3edfea.png)

That are ALL the changes I made. Then, I opened the index.html file in my browser and it shows this: The base map is rendered correctly, but no simulation is rendered (I am expecting something from gama_client.js). 

![Screen Shot 2023-02-08 at 11 38 57 AM](https://user-images.githubusercontent.com/22874361/217598369-16338a71-4bfa-438f-948a-79420c07651d.png)

Once I loaded the index.html, the terminal says: 
0:0:0:0:0:0:0:1 entered the room!
 
And there are no other error messages. I am not sure how to interpret the error warnings in the browser inspector. 
 
I tried the following approaches, and it did not solve the problem: 
-       Change to a different port 
-       Change to a different html (e.g., syntax.html)
-       Change to a different browser 
 
Any idea of what to go next will be appreciated because I am clueless. Thanks!

**Comment by hqnghi88** [comment]
Please try again with my new commit (of course with the latest alpha version of GAMA).

**Comment by xiaofanliang** [comment]
Hi! I re-downloaded the alpha version of the GAMA, clone the new repo, and repeat my steps above, but the same issues persist. Am I supposed to see the simulation running from gama_client.js? Are my steps above the right way to load the examples? 

![Screen Shot 2023-02-09 at 3 31 42 PM](https://user-images.githubusercontent.com/22874361/217930303-7a63dbb5-fde3-41c9-b18f-f8f9f5988ec8.png)

**Comment by hqnghi88** [comment]
Your steps are right, what is in console tab (you are showing network, please see in console)?

**Comment by xiaofanliang** [comment]
You can see the console tab output on the bottom right of the image. It did not report any error message.

**Comment by hqnghi88** [comment]
Yes it is supposed to open index.html , ws is a websocket and browser address cant process that kind. Nothing in the terminam where gamaserver launched?

**Comment by hqnghi88** [comment]
You should pull gama.client repo, i changed the code in that repo, not the gama repo (just be sure you are using the latest alpha)

**Comment by xiaofanliang** [comment]
Yes, I pulled the gama.client repo, not the GAMA repo, and installed the alpha version: GAMA_1.9.0_MacOS_with_JDK_02.09.23_4b82ffc7.dmg

**Comment by hqnghi88** [comment]
Send me your gamaclient.js

**Comment by xiaofanliang** [comment]
Do you need to have JAVA or Eclipse installed or configured in a specific way? I just restarted my computer fresh and rerun the process on my Mac M1 and my friend's window system (both installed with Alpha version. I installed GAMA_1.9.0_MacOS_M1_02.09.23_4b82ffc7.dmg and he installed GAMA_1.9.0_Windows_with_JDK_02.09.23_4b82ffc7.exe). I configured path to the model through the application, and he configured the path to the model through git version of GAMA. both of us ran into JAVA-related issues in the server. 

My error starts even before GAMA can listen on the port: 
<img width="570" alt="screenshot" src="https://user-images.githubusercontent.com/22874361/217991764-b8bcb282-5cfe-439e-adcb-0258315171dc.png">

His error starts after the listening: 
![329840276_1367576724061970_74724495388094605_n](https://user-images.githubusercontent.com/22874361/217992048-b93740e2-7d96-4f46-88a2-63d27451e99f.png)

I attached my gamaclient.js in case you still want to take a look: 
https://drive.google.com/file/d/1FyDZ6c16nNATJv3YclFd_vSX7H6yeHvI/view?usp=sharing

Thanks for digging into this rabbit hole.

**Comment by hqnghi88** [comment]
Hi i will see your js. The windows machine must have admin right access or it will alway return randomly error….

**Comment by hqnghi88** [comment]
I checked your js and it's perfect, do you have any changes in GAMA.js so that it is not updated? Even if the path it should show a message as:
<img width="696" alt="Screenshot 2023-02-10 at 15 08 44" src="https://user-images.githubusercontent.com/6105384/218036895-d5e86270-bc3b-4cb8-9265-3d14f239efa2.png">
Regarding the 2 error message, it is relate with the path and access right, please try with the highest priviledges on each OS (sudo or administrator)

**Comment by xiaofanliang** [comment]
@hqnghi88 I saw that that error message (Invalid LngLat object) shows up at one point in my trial at the window computer. It never shows in the Mac version. I will try to set the privileges and see if that works.

**Comment by xiaofanliang** [comment]
> I think the `Could not find or load main class org...` error could be because you didn't run the bash script from the `headless` directory?

It shows the same error even if I start in the headless directory. 
![screen](https://user-images.githubusercontent.com/22874361/218162287-77757940-9937-48fa-a39a-11bc5c7e3ba0.png)

**Comment by neo** [comment]
It seems like `realpath` was introduced in this commit https://github.com/gama-platform/gama/commit/240559e36900b6c58c24b0821f249b49e400872c in `gama-headless.sh` but it's actually only available in linux but not in mac?

**Comment by xiaofanliang** [comment]
I think @neo is right. I switched my GAMA back to 1.8 version and the server can start fine without the JAVA issue (but then the rendering issues loop back to what I had at the very beginning, which is no error messages whatsoever but cannot load simulation). 

I followed @neo's suggestion and go into the commit above and change this line 
`if ! "$( dirname $( realpath "${BASH_SOURCE[0]}" ) )"`
back to the previous commit 
`if ! "$( dirname "${BASH_SOURCE[0]}" )"` 

and then start the server with GAMA 1.9 version, and the index.html is running smoothly like below
![s](https://user-images.githubusercontent.com/22874361/218186306-ac0ed960-1517-4d74-8f71-19bd02311739.png)

and syntax.html is reporting statistics 
![ss](https://user-images.githubusercontent.com/22874361/218186659-4ff2f201-7e8e-4ab0-a0e1-5f54f3bb607b.png)

**Comment by hqnghi88** [comment]
Hi,
I am not really a pro user mac but im currently can launch the bash headless.sh on m1. So may be you can open an issue on gama repository if you think the scripts must be changed.
The syntax.html is not pre-defined statistics but it s a real simulation on an example server.
Regarding simpleGUI , it is as you tested, some specific model cannot launch for the moment.

**Comment by xiaofanliang** [comment]
> It seems like `realpath` was introduced in this commit [gama-platform/gama@240559e](https://github.com/gama-platform/gama/commit/240559e36900b6c58c24b0821f249b49e400872c) in `gama-headless.sh` but it's actually only available in linux but not in mac?
