### ISSUE TITLE
Headless client documentation outdated

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.client#3]
**Describe the bug**
The documentation is currently out sync with the repo itsel 

https://gama-platform.org/wiki/HeadlessServer#hello-world-visualization-in-mapbox

- ```Javascript/gama_client.js``` is now in ```js/gama_client.js```
The Javascript folder is empty in the source and the 

```chain_messages.js```and ```Javascript/message_example``` do not exist anymore 

We just need to converge between the doc and the code. To discuss with @hqnghi88

**Comment by lesquoyb** [comment]
I updated the documentation a bit, can you tell me if it's good now ?
[https://gama-platform.org/wiki/next/HeadlessServer#hello-world-visualization-in-mapbox](https://gama-platform.org/wiki/next/HeadlessServer#hello-world-visualization-in-mapbox)

**Comment by agrignard** [comment]
Ok great @lesquoyb the documentation (on the next version not on the current website) is up to date and working (with this modification https://github.com/gama-platform/gama/issues/3617)
