### ISSUE TITLE
Client not running with customized model

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.client#4]
I am trying to make the client architecture working with my own model (that use to work in the 1.8)

In order to plug it to Gama 

1. Clone this repo: https://github.com/VCityTeam/UD_ReAgent_ABM/
2. In gama.client comment this lines:

````
var ABSOLUTE_PATH_TO_GAMA = '/Users/hqn88/git/';
var modelPath = ABSOLUTE_PATH_TO_GAMA + 'gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml';
var experimentName = 'road_traffic';
var species1Name = 'people';
var attribute1Name = 'objective';
var species2Name = 'building';
var attribute2Name = 'type';
`````
and uncomment this one (be sure it's poiting to the right folder where you have downloaded ReAgent
````
const modelPath = '/Users/arno/Projects/GitHub/UD_ReAgent_ABM/ReAgent/models/Gratte_Ciel_Demo.gaml';
const experimentName = 'Demo';
const species1Name = 'people';
const attribute1Name = 'type';
//const species2Name = 'building';
//const attribute2Name = 'type';
````
3. run gama headless
4. Open index.html

You should see this:
<img width="1039" alt="Screenshot 2023-02-21 at 11 42 22" src="https://user-images.githubusercontent.com/3928502/220323210-1ceb4902-c302-47a6-abaa-8dbe235b8811.png">

After few iteration I have the following error in my browser console
`````

> Error: J"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.callback (gama_client.js:93:20)
    at wSocket.onmessage (GAMA.js:53:48)
`````

**Comment by hqnghi88** [comment]
It is releted with the mysterious error "Linering".... A workaround is to remove the line geometry shape<-circle(2#m) in ReAgent model. I m digging again for the error

**Comment by hqnghi88** [comment]
https://github.com/gama-platform/gama/issues/3639 a fix has commit from the suggestion of this issue in gama core. please try with new alpha release (1hour later)
